{
  "hash": "5cd5f0a739e80dde259ea474b9727edc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Check your data\"\ndescription: \"Find out how good your tracking really is — confidence, gaps, and when they happen — before changing anything.\"\norder: 3\n---\n\n\n\nTracking data is never perfect. Keypoints get occluded, the tracker guesses,\nand a guess looks exactly like a measurement once it's written to file — a pair\nof plausible coordinates, indistinguishable from the real thing.\n\n[anicheck](https://animovement.dev/anicheck) exists to tell them apart. Its\nfunctions only *report*: they take an aniframe and give you back a summary,\nleaving your data untouched. Cleaning comes next, once you know what you're\ncleaning.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(animovement)\n\nmovement <- read_sleap(get_sample_data(\"sleap\")) |>\n  set_sampling_rate(30)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Downloading sleap data...\n```\n\n\n:::\n:::\n\n\n## How confident was the tracker? {#sec-confidence}\n\nPose-estimation tools score every point they place. `check_confidence()`\nsummarises those scores per keypoint:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_confidence(movement)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ── Check: tracking confidence \n#> Confidence for 6 keypoints (median [min]):\n#> • individual1 | centre: 0.93 [0.29]\n#> • individual1 | left_ear: 0.96 [0.00]\n#> • individual1 | right_ear: 0.89 [0.00]\n#> • individual1 | snout: 0.78 [0.00]\n#> • individual1 | tail_base: 0.96 [0.00]\n#> • individual1 | tail_end: 0.77 [0.00]\n```\n\n\n:::\n:::\n\n\nAlready informative: the snout and tail end are tracked far less confidently\nthan the centre or the ears — which makes sense, they're the parts that\ndisappear when the mouse turns. Pair the check with `plot()` to see the whole\ndistribution rather than two numbers:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(check_confidence(movement))\n```\n\n::: {.cell-output-display}\n![Confidence per keypoint. The spike at zero is the tracker admitting it had no idea.](check-data_files/figure-html/plot-conf-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThis is the plot that picks your threshold. The bulk of each keypoint sits near\n1, with a separate clump at zero and a thin tail between — so a cut somewhere\naround 0.6 removes the failures without touching the good tracking. Where\nexactly to cut is a judgement call about your data, and this plot is how you\nmake it rather than guess it.\n\n::: {.callout-note}\n## Confidence isn't a probability\nScores are whatever the tracker chose to emit. SLEAP's run past 1 in this\nrecording, and a \"0.9\" from one tool means nothing about a \"0.9\" from another.\nRead the distribution, don't import a threshold from someone else's paper.\n:::\n\n## Where are the gaps? {#sec-gaps}\n\nMissing values are the other half of the story. `check_na_gapsize()` reports how\nmany there are and, more usefully, how they're distributed between short\ndropouts and long absences:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_na_gapsize(movement)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ── Check: missing-value gap sizes \n#> Tracking x: 9230 missing (8.3%) across 1019 gaps, longest 197 frames.\n#> By group (individual and keypoint):\n#> • individual1 | centre: 79 gaps, longest 108\n#> • individual1 | left_ear: 87 gaps, longest 108\n#> • individual1 | right_ear: 86 gaps, longest 108\n#> • individual1 | snout: 331 gaps, longest 197\n#> • individual1 | tail_base: 109 gaps, longest 108\n#> • individual1 | tail_end: 327 gaps, longest 136\n```\n\n\n:::\n:::\n\n\nEight percent of this recording is missing, but that number hides the shape of\nthe problem: the snout alone accounts for 331 separate gaps, one of them 197\nframes long. Plotting one keypoint at a time shows the shape clearly:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmovement |>\n  dplyr::filter(keypoint == \"snout\") |>\n  check_na_gapsize() |>\n  plot()\n```\n\n::: {.cell-output-display}\n![Gap sizes for the snout. Most gaps are a handful of frames; the red bars count gaps, the blue bars count the missing values they add up to.](check-data_files/figure-html/plot-gaps-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThat distinction matters for the next step. A one-frame gap is worth\ninterpolating across — the mouse can't have gone far. A 197-frame gap is nearly\nseven seconds, and anything you draw across it is invention.\n\n::: {.callout-tip}\n## Plotting several groups at once\nThese check plots put each group in its own panel, so with six keypoints you'll\nwant a taller figure — `fig-height: 10` or so — before they become readable.\nOne keypoint at a time is usually easier to read anyway.\n:::\n\n## When do they happen? {#sec-timing}\n\nGaps clustered in one stretch mean something different from gaps sprinkled\nevenly — a lighting change, say, versus a keypoint the model was never good at.\n`check_na_timing()` splits the recording into intervals and shows what fraction\nof each is missing:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_na_timing(movement)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ── Check: timing of missing values \n#> Tracking x across 110910 frames - 9230 missing (8.3%) in 1019 gaps.\n#> By group (individual and keypoint):\n#> • individual1 | centre: 2.7% missing in 79 gaps (longest 108)\n#> • individual1 | left_ear: 2.8% missing in 87 gaps (longest 108)\n#> • individual1 | right_ear: 2.9% missing in 86 gaps (longest 108)\n#> • individual1 | snout: 24.3% missing in 331 gaps (longest 197)\n#> • individual1 | tail_base: 3.8% missing in 109 gaps (longest 108)\n#> • individual1 | tail_end: 13.5% missing in 327 gaps (longest 136)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmovement |>\n  dplyr::filter(keypoint == \"snout\") |>\n  check_na_timing() |>\n  plot()\n```\n\n::: {.cell-output-display}\n![When the snout goes missing. Nearly half of some early intervals, barely any of others.](check-data_files/figure-html/plot-timing-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nHere it's spread across the whole recording, with a couple of bad patches near\nthe start and around eight minutes in — the mouse in the closed arms, out of\nsight of the camera. Nothing to fix in the setup; something to be careful about\nwhen interpreting behaviour from those stretches.\n\n## What we learned {#sec-summary}\n\nThree checks, three decisions for the [next guide](process-data.qmd):\n\n- The maze occupies roughly x ∈ [300, 1010], y ∈ [0, 690]; the few points\n  outside it are impossible, so they can go.\n- Confidence separates cleanly around **0.6**, so that's where we'll mask.\n- Most gaps are a few frames long and safe to interpolate; a handful run to\n  nearly 200 frames and are not.\n- The missing data is spread through the recording rather than concentrated in\n  one broken stretch, so there's no reason to discard part of it.\n\nNext: [process the trajectories](process-data.qmd).\n",
    "supporting": [
      "check-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}